init:
  - git config --global core.autocrlf true
services:
  - mssql2014
  - mysql
environment:
  SQLSERVER_CONNECTION_STRING: Data Source=.;Initial Catalog=tempdb;Integrated Security=True
  MYSQL_CONNECTION_STRING: server=localhost;uid=root;pwd=Password12!;database=yessql;
build_script:
  - SET MYSQL_PWD=Password12!
  - '"C:/Program Files/MySQL/MySQL Server 5.7/bin/mysql" -e "create database yessql;" --user=root'
  - build.cmd verify
clone_depth: 1
test: off
deploy: off
os: Visual Studio 2015